### ISSUE TITLE
Examples for Java and Go missing

### ISSUE THREAD

**Issue by ledex** [spaceuptech/space-docs#2]
In `essentials -> queries` there are no examples for Java and Go.

**Comment by YourTechBud** [comment]
We are depreciating the all drivers apart from js. The recommended way to us SC is via the GraphQL api.

**Comment by ledex** [comment]
Right, as discussed. But you should inform in the docs about the recommended way. I couldn't find it there.

**Comment by YourTechBud** [comment]
That makes sense.

@Jayesh333 lets just remove the golang and java clients from the docs.
